### ISSUE TITLE
Reference sample changed

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/dragenge_post_processing#2]
GIAB reference sample has changed from 18M01315 to 18M01316, needs to be updated in config here - 
https://github.com/AWGL/dragenge_post_processing/blob/9b7a3008f94729863efe23449e0906e2132523cf/config/IlluminaTruSightOne/IlluminaTruSightOne_pbs.config#L34

**Comment by josephhalstead** [comment]
closed in pull request #3
