### ISSUE TITLE
BUG old_variant_database_vcf folder removed so autoqc gets stuck

### ISSUE THREAD

**Issue by LauraMcCluskey7** [AWGL/dragenge_post_processing#28]
# Describe the bug
 The "old_variant_database_vcf" folder  is removed by this version of the pipeline. This is required by autoqc to be able to calculate the number of variants, so autoqc gets stuck for this run. 
 
# Reproduce the bug
This error occurred in run 221014_A01771_0102_AH7GWLDRX2

**Comment by SophieS9** [comment]
Fixed in https://github.com/AWGL/auto_qc/pull/106
